#!/bin/bash

run=false
apply=false

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [options] <dir> ...

The purpose of kreate is calling kreate.sh to create kustomize files
and then execute kustomize, and possibly use kubectl apply
    -h|--help|help     display this help and exit
    -v|--verbose       verbose mode.
    -n|--no-files      do not kreate files
    -r|--run|run       run 'kustomize build'
    -a|--apply|apply   run 'kustomize build | kubectl apply -f -'
EOF
}

while :; do
    case $1 in
        -h|help|--help)
            show_help
            exit 0
            ;;
        -v|--verbose)
            export SILENT=false
            ;;
        -n|--no-files)
            export KREATE_NO_FILES=true
            ;;
        -r|--run|run)
            run=true
            ;;
        -a|--apply|apply)
            apply=true
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac
    shift
done




kreate_apply() {
    $SILENT || echo kustomize build $1 \| kubectl apply -f -
    kustomize build $1 | kubectl apply -f -
}
kreate_run() {
    $SILENT || echo kustomize build $1
    kustomize build $1
}

if [[ -f  ./.kreate_profile ]] ;then
  source ./.kreate_profile
elif [[ -f  ~/.kreate/profile ]] ;then
  source ~/.kreate/profile
elif [[ -f  /etc/kreate/profile ]] ;then
  source /etc/kreate/profile
fi

for f in $*
do
    if [[ -x $f/kreate.sh ]]; then
        $SILENT || echo Starting $f/kreate.sh
        $f/kreate.sh
    else
        $SILENT && echo Skipping $f/kreate.sh
    fi
    if $apply ; then
        kreate_apply $f
    elif $run; then
        kreate_run $f
    fi
done
