#!/usr/bin/env bash
# Script Name: render-manifests
# Description: render helm manifests for applications and environments
# Author: Mark Hooijkaas
# Sourcecode: https://github.com/kisst-org/kreate-hooy/
# License: Apache License version 2.0
# Install or update to newest version with following command:
#   curl -OL https://raw.githubusercontent.com/kisst-org/kreate-hooy/refs/heads/main/kreate && chmod 755 kreate

set -eu
shopt -s extglob
script_name="${0}"

source_files_from_lib() {
    dir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))/lib
    if ${load_modules_from_lib:-true}; then
        for file in $dir/*.lib; do
            source $file
        done
    fi
}

main() {
    source_files_from_lib
    init_logging "${@}"
    init_all_modules
    read_config
    parse_options "${@}"
    forall-appenvs
}

main "${@}"
